# Generated by Django 4.1.3 on 2022-11-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_userguess_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userguess',
            name='date',
        ),
        migrations.AddField(
            model_name='userguess',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
