# Generated by Django 4.1.3 on 2022-11-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_emailfornotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailfornotification',
            name='session_id',
            field=models.CharField(db_index=True, default='', max_length=30),
            preserve_default=False,
        ),
    ]
