# Generated by Django 4.1.3 on 2022-12-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0008_emailfornotification_session_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailForNotification",
        ),
    ]
