# Generated by Django 4.1.3 on 2022-12-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words", "0009_delete_emailfornotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daykeyword",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
